cms/urls.py
from django.conf.urls.defaults import *
from cms import settings
from cms.views import details

urlpatterns = (
    # Public pages
    url(r'^$', details, {'slug':''}, name='pages-root'),
    url(r'^(?P<slug>[0-9A-Za-z-_//]+)/$', details, name='pages-details-by-slug'),
)

if settings.CMS_APPLICATIONS_URLS:
    """If there are some application urls, add special resolver, so we will
    have standard reverse support.
    """
    from cms.appresolver import dynamic_app_regex_url_resolver
    urlpatterns = (dynamic_app_regex_url_resolver, ) + urlpatterns
    
urlpatterns = patterns('', *urlpatterns)

urls.py
from django.conf.urls.defaults import *
import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^mlas_site/', include('mlas_site.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     (r'^admin/(.*)', admin.site.root),
)


if settings.DEBUG:
    urlpatterns+= patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
    )

urlpatterns += patterns('',
    url(r'^', include('cms.urls')),
)

cms/plugins/file/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin
from os.path import join, basename, splitext, exists
import math

from cms import settings as cms_settings
from django.conf import settings

if 'reversion' in settings.INSTALLED_APPS:
    import reversion

class File(CMSPlugin):
    """
    Plugin for storing any type of file.
    
    Default template displays download link with icon (if available) and file size.
    
    Icons are searched for within <MEDIA_ROOT>/<CMS_FILE_ICON_PATH> 
    (CMS_FILE_ICON_PATH is a plugin-specific setting which defaults to "<CMS_MEDIA_PATH>/images/file_icons")
    with filenames of the form <file_ext>.<icon_ext>, where <file_ext> is the extension
    of the file itself, and <icon_ext> is one of <CMS_FILE_ICON_EXTENSIONS>
    (another plugin specific setting, which defaults to ('gif', 'png'))
    
    This could be updated to use the mimetypes library to determine the type of file rather than
    storing a separate icon for each different extension.
    
    The icon search is currently performed within get_icon_url; this is probably a performance concern.
    """
    file = models.FileField(_("file"), upload_to=CMSPlugin.get_media_path)
    title = models.CharField(_("title"), max_length=255, null=True, blank=True)
    # CMS_ICON_EXTENSIONS and CMS_ICON_PATH are assumed to be plugin-specific, and not included in cms.settings
    # -- they are therefore imported from django.conf.settings
    ICON_EXTENSIONS = getattr(settings, "CMS_FILE_ICON_EXTENSIONS", ('gif', 'png'))
    ICON_PATH = getattr(settings, "CMS_FILE_ICON_PATH", join(cms_settings.CMS_MEDIA_PATH, "images", "file_icons"))
    
    def get_icon_url(self):
        base = join(self.ICON_PATH, self.get_ext())
        for ext in self.ICON_EXTENSIONS:
            relative = "%s.%s" % (base, ext)
            if exists(join(settings.MEDIA_ROOT, relative)): 
                return join(settings.MEDIA_URL, relative)
        return None
        
    def file_exists(self):
        return exists(self.file.path);
        
    def get_file_name(self):
        return basename(self.file.path)
        
    def get_ext(self):
        return splitext(self.get_file_name())[1][1:]
        
    def __unicode__(self):
        if self.title: return self.title;
        return self.get_file_name();

if 'reversion' in settings.INSTALLED_APPS:        
    reversion.register(File, follow=["cmsplugin_ptr"])

cms/plugins/flash/models.py
import re
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from cms.models import CMSPlugin
from os.path import basename

if 'reversion' in settings.INSTALLED_APPS:
    import reversion


class Flash(CMSPlugin):
    file = models.FileField(_('file'), upload_to=CMSPlugin.get_media_path, help_text=_('use swf file'))
    width = models.CharField(_('width'), max_length=6)
    height = models.CharField(_('height'), max_length=6)    
    
    def get_height(self):
        return fix_unit(self.height)
    
    def get_width(self):
        return fix_unit(self.width)    
        
    def __unicode__(self):
        return u"%s" % basename(self.file.path)

if 'reversion' in settings.INSTALLED_APPS:        
    reversion.register(Flash, follow=["cmsplugin_ptr"])


def fix_unit(value):
    if not re.match(r'.*[0-9]$', value):
        # no unit, add px
        return value + "px"
    return value 

cms/plugins/link/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin, Page
from django.conf import settings

if 'reversion' in settings.INSTALLED_APPS:
    import reversion

class Link(CMSPlugin):
    """
    A link to an other page or to an external website
    """
    
    name = models.CharField(_("name"), max_length=256)
    url = models.URLField(_("link"), verify_exists=True, blank=True, null=True)
    page_link = models.ForeignKey(Page, verbose_name=_("page"), blank=True, null=True, help_text=_("A link to a page has priority over a text link."))
        
    def __unicode__(self):
        return self.name

if 'reversion' in settings.INSTALLED_APPS:        
    reversion.register(Link, follow=["cmsplugin_ptr"])

cms/plugins/picture/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin
from os.path import basename

from django.conf import settings

if 'reversion' in settings.INSTALLED_APPS:
    import reversion

class Picture(CMSPlugin):
    """
    A Picture with or without a link
    """
    
    image = models.ImageField(_("image"), upload_to=CMSPlugin.get_media_path)
    url = models.CharField(_("link"), max_length=255, blank=True, null=True, help_text=_("if present image will be clickable"))
    alt = models.CharField(_("alternate text"), max_length=255, blank=True, null=True, help_text=_("textual description of the image"))
    
    def __unicode__(self):
        if self.alt:
            return self.alt[:40]
        return u"%s" % basename(self.image.path)

if 'reversion' in settings.INSTALLED_APPS:        
    reversion.register(Picture, follow=["cmsplugin_ptr"])
    

cms/plugins/snippet/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin
from django.conf import settings

if 'reversion' in settings.INSTALLED_APPS:
    import reversion

# Stores the actual data
class Snippet(models.Model):
    """
    A snippet of HTML or a Django template
    """
    name = models.CharField(_("name"), max_length=255, unique=True)
    html = models.TextField(_("HTML"), blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

# Plugin model - just a pointer to Snippet
class SnippetPtr(CMSPlugin):
    snippet = models.ForeignKey(Snippet)

    class Meta:
        verbose_name = _("Snippet")

if 'reversion' in settings.INSTALLED_APPS:
    # We don't both with SnippetPtr, since all the data is actually in Snippet
    reversion.register(Snippet)

cms/plugins/text/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin
from django.conf import settings
from django.utils.html import strip_tags
from django.utils.text import truncate_words
from cms.plugins.text.utils import plugin_admin_html_to_tags,\
    plugin_tags_to_admin_html

if 'reversion' in settings.INSTALLED_APPS:
    import reversion

class Text(CMSPlugin):
    """A block of content, tied to a page, for a particular language"""
    body = models.TextField(_("body"))
    
    def _set_body_admin(self, text):
        self.body = plugin_admin_html_to_tags(text)

    def _get_body_admin(self):
        return plugin_tags_to_admin_html(self.body)

    body_for_admin = property(_get_body_admin, _set_body_admin, None,
                              """
                              body attribute, but with transformations
                              applied to allow editing in the
                              admin. Read/write.
                              """)

    
    def __unicode__(self):
        return u"%s" % (truncate_words(strip_tags(self.body), 3)[:30]+"...")

if 'reversion' in settings.INSTALLED_APPS:        
    reversion.register(Text, follow=["cmsplugin_ptr"])
    

cms/admin/forms.py
from django import forms
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _, ugettext_lazy
from django.conf import settings
from django.forms.util import ErrorList
from cms.settings import CMS_LANGUAGES, CMS_UNIQUE_SLUGS, CMS_APPLICATIONS_URLS, CMS_FLAT_URLS
from cms.models import Page, Title
from cms.urlutils import any_path_re

class PageForm(forms.ModelForm):
    APPLICATION_URLS = (('', '----------'), ) + CMS_APPLICATIONS_URLS
    
    title = forms.CharField(label=_("Title"), widget=forms.TextInput(),
        help_text=_('The default title'))
    menu_title = forms.CharField(label=_("Menu Title"), widget=forms.TextInput(),
        help_text=_('Overwrite what is displayed in the menu'), required=False)
    page_title = forms.CharField(label=_("Page Title"), widget=forms.TextInput(),
        help_text=_('Overwrites what is display at the top of your browser or in bookmarks'), required=False)
    language = forms.ChoiceField(label=_("Language"), choices=CMS_LANGUAGES,
        help_text=_('The current language of the content fields.'))
    slug = forms.CharField(label=_("Slug"), widget=forms.TextInput(),
        help_text=_('The part of the title that is used in the url'))
    application_urls = forms.ChoiceField(label=_('Application'), 
        choices=APPLICATION_URLS, required=False,  
        help_text=_('Hook application to this page.'))
    overwrite_url = forms.CharField(label=_('Overwrite url'), max_length=255, required=False,
        help_text=_('Keep this field empty if standard path should be used.'))
    redirect = forms.CharField(label=_('Redirect'), max_length=255, required=False,
        help_text=_('Redirects to this URL.'))
    meta_description = forms.CharField(label='Description meta tag', required=False, widget=forms.Textarea,
        help_text=_('A description of the page sometimes used by search engines.'))
    meta_keywords = forms.CharField(label='Keywords meta tag', max_length=255, required=False,
        help_text=_('A list of comma seperated keywords sometimes used by search engines.'))    
    
    class Meta:
        model = Page
    
    def clean(self):
        cleaned_data = self.cleaned_data
        if 'slug' in cleaned_data.keys():
            slug = cleaned_data['slug']
        else:
            slug = ""
        
        page = self.instance
        lang = cleaned_data['language']
        parent = cleaned_data['parent']
        if CMS_UNIQUE_SLUGS:
            titles = Title.objects.filter(slug=slug)
        else:
            titles = Title.objects.filter(slug=slug, language=lang)        
        if not CMS_FLAT_URLS:
            titles = titles.filter(page__parent=parent)
        if self.instance.pk:
            titles = titles.exclude(language=lang, page=page)
        if titles.count():
            self._errors['slug'] = ErrorList([ugettext_lazy('Another page with this slug already exists')])
            del cleaned_data['slug']
        return cleaned_data
    
    def clean_slug(self):
        slug = slugify(self.cleaned_data['slug'])
        return slug
    
    def clean_reverse_id(self):
        id = self.cleaned_data['reverse_id']
        if id:
            if Page.objects.filter(reverse_id=id).exclude(pk=self.instance.pk).count():
                raise forms.ValidationError(ugettext_lazy('A page with this reverse url id exists already.'))
        return id

    def clean_overwrite_url(self):
        url = self.cleaned_data['overwrite_url']
        if url:
            if not any_path_re.match(url):
                raise forms.ValidationError(ugettext_lazy('Invalid url, use /my/url format.'))
        return url
    
    def clean_sites(self):
        sites = self.cleaned_data['sites']
        if self.cleaned_data['parent'] != None:
            parent_sites = self.cleaned_data['parent'].sites.all().values_list('id', flat=True)
            for site in sites:
                if not site.pk in parent_sites:
                    raise forms.ValidationError(ugettext_lazy('The parent of this page is not on the site %(site)s') % {'site':site } )
        return sites
        

cms/plugins/flash/forms.py
from django import forms
from cms.plugins.flash.models import Flash

class FlashForm(forms.ModelForm):
    
    class Meta:
        model = Flash
        exclude = ('page', 'position', 'placeholder', 'language', 'plugin_type')

cms/plugins/text/forms.py
from django.forms.models import ModelForm
from cms.plugins.text.models import Text
from django import forms


class TextForm(ModelForm):
    body = forms.CharField()
    
    class Meta:
        model = Text
        exclude = ('page', 'position', 'placeholder', 'language', 'plugin_type')

cms/plugins/text/templates/cms/plugins/widgets/wymeditor.html
{% load i18n %}
<script type="text/javascript">

// Global var, for storing callbacks, see below.
var editPluginPopupCallbacks = {};

// Global function, needed for popup window to call the parent via opener.dismissEditPluginPopup
function dismissEditPluginPopup(win, plugin_id, icon_src, icon_alt) {
    // This is called after user presses 'Save' in popup.
    win.close();
    var callback = editPluginPopupCallbacks[plugin_id];
    if (callback != null) {
        callback(plugin_id, icon_src, icon_alt);
    }
}

// TODO - move this html escape function somewhere nicer

function escapeHtml(html) {
    return html.replace(/&/g,"&amp;")
        .replace(/\"/g,"&quot;")
        .replace(/</g,"&lt;")
        .replace(/>/g,"&gt;");
}

$(document).ready(function(){
    $('#id_{{ name }}').wymeditor({
        lang: '{{ language }}',
        skin: 'django',
        skinPath: "{{ CMS_MEDIA_URL }}javascript/wymeditor/skins/django/",
        updateSelector: 'input[type=submit],',
        updateEvent: 'click',
		logoHtml: '',
		toolsItems: [
			    {{ WYM_TOOLS }}
			],
		containersItems: [
		        {{ WYM_CONTAINERS }}
		    ],
		classesItems: [
			    {{ WYM_CLASSES }}
			],
		editorStyles: [
			{{ WYM_STYLES }}
			],
        postInit: function(wym) {
			 //wym.resizable({handles: "s", maxHeight: 600});
            //construct the insertLinkButton html
            html = '<div class="plugin-select-holder">'
				 + '<select name="plugins">'
				 + '<option value="" selected="selected">{% trans "Available Plugins" %}</option>'{% for p in installed_plugins %}
      			 + '<option value="{{ p.value }}">{{ p.name }}</option>'{% endfor %}
    			 + '</select>'
    			 + '<span class="insert-object addlink">{% trans "Insert plugin" %}</span>'
    			 + '<span class="edit-object changelink">{% trans "Edit selected plugin" %}</span>'
  				 + '</div>';
            //add the button to the tools box
            jQuery(wym._box)
            .find(wym._options.toolsSelector + wym._options.toolsListSelector)
            .append(html);
            // Enable the placeholderbridge plugin, to allow
            // the placeholder controls to talk to editor
            wym.placeholderbridge({'name': '{{ name }}'});
            init_buttons("{{ name }}");
        },
        //handle click event on dialog's submit button
        postInitDialog: function( wym, wdw ) {
     
        }
    });
	  /* General functions */
    function get_editor(placeholder) {
        // Find the placeholder text editor widget
        if (typeof(PlaceholderEditorRegistry) == "undefined") {
            // This could occur if javascript defining PlaceholderEditorRegistry
            // has not been loaded for some reason.
            alert("{% trans "A programming error occurred - cannot find text editor widgets." %}");
            return null;
        }
        return PlaceholderEditorRegistry.retrieveEditor(placeholder);
    }

    function edit_object(obj_id) {
        // Pop up window for editing object.
        window.open("edit-plugin/" + obj_id + "/?_popup=1",
                    "Edit plugin object",
                    "menubar=no,titlebar=no,toolbar=no,resizable=yes"
                      + ",width=800,height=300,top=0,left=0,scrollbars=yes"
                      + ",location=no"
                   );
    }

    function plugin_admin_html(plugin_id, icon_src, icon_alt) {
        return '<img src="' + escapeHtml(icon_src) + '" ' +
            'alt="'+ escapeHtml(icon_alt) + '" ' +
            'id="plugin_obj_' + plugin_id + '"/>';
    }

    /* onclick for 'Insert object' */
	
	function init_buttons(placeholder){
		$('span.insert-object').click(function(){
			var select = $(this).parent().children("select");
			var pluginvalue = select.attr('value');
			var splits = window.location.href.split("?")[0].split("/");
			var parent_id = Number(splits[splits.length - 2]);
			var language = $('#id_language').attr('value');
			
			if (pluginvalue == "") {
				alert("{% trans "Please select a plugin type." %}");
				return;
			}
			
			var texteditor = get_editor(placeholder);
			if (texteditor == null || texteditor.insertText == null) {
				alert("{% trans "Text editor does not support inserting objects." %}");
				return;
			}
			// First create db instance using AJAX post back
			$.post("add-plugin/", {
				parent_id: parent_id,
				plugin_type: pluginvalue
			}, function(data){
				if ('error' != data) {
					// Successfully created, data is pk of object, but object
					// is 'blank'. We now want to show the edit popup.
					
					// We only want to insert the text if the user actually
					// *saved* the object.  We don't have modal dialogs, so we
					// register a callback against the id number.  This callback
					// is called by dismissEditPluginPopup().
					var plugin_id = data;
					editPluginPopupCallbacks[data] = function(plugin_id, icon_src, icon_alt){
						texteditor.insertText(plugin_admin_html(plugin_id, icon_src, icon_alt));
						editPluginPopupCallbacks[data] = null; // Unbind callback
					};
					
					// Show popup for editing
					edit_object(plugin_id);
				}
			}, "html");
			
		}).css("cursor", "pointer").css("margin", "5px");
		
		/* onclick for 'Edit selected object' */
		$('span.edit-object').click(function(){
			var texteditor = get_editor(placeholder);
			if (texteditor == null || texteditor.selectedObject == null) {
				alert("{% trans "Text editor does not support editing objects." %}");
				return;
			}
			var imgobj = texteditor.selectedObject();
			if (imgobj == null) {
				alert("{% trans "No object selected." %}");
				return;
			}
			if (imgobj.id == null || imgobj.id.indexOf("plugin_obj_") != 0) {
				alert("{% trans "Not a plugin object" %}");
				return;
			}
			var plugin_id = imgobj.id.substr("plugin_obj_".length);
			edit_object(plugin_id);
		}).css("cursor", "pointer").css("margin","5px");
	}
});
    </script>